### ISSUE TITLE
限定微博地点和抓取用户个人信息

### ISSUE THREAD

**Issue by lovesnacks** [CUHKSZ-TQL/WeiboSpider_SentimentAnalysis#1]
![image](https://user-images.githubusercontent.com/41772072/57059642-d992cd80-6ce8-11e9-9030-00e015de626c.png)
1.请问这段抓取个人信息的代码不能用吗？
2.配置好环境以后直接在redis_init.py中填写需要的关键词和时间段就可以运行了吗？如果想限定发微博的地点，能否直接在url_format中加一个“region=custom:xx:xx”呢？
3.如果查找的关键词有很多，在数据库中如何区分呢?能否增加一列字段为keyword？
4.还要就是爬的过程中出现error：list index out of range是什么情况呢

**Comment by seaweiqing** [comment]
您好，以下是问题的解答：
1. 抓取个人信息的这部分代码也是可以用的，只是我们最终没有用到这个部分，就把它注释掉了，如果有需要的话您把这个部分的注释去掉就行。
2. 配置好之后改对应关键词和时间段就行，如果需要限制微博类型或者地点就根据url的格式加上新的限制条件。
3. 您的意思是指查找具有某几个关键词的微博吗？可以考虑建个字典对url进行更新。数据库中可以添加相应的字段进行区分。
4. 您需要把这个问题再具体一点，我们也不太清楚您说的具体是哪个部分出现了这个错误，我们之前运行的时候是没有出现这个问题的。

**Comment by lovesnacks** [comment]
> 您好，以下是问题的解答：
> 
> 1. 抓取个人信息的这部分代码也是可以用的，只是我们最终没有用到这个部分，就把它注释掉了，如果有需要的话您把这个部分的注释去掉就行。
> 2. 配置好之后改对应关键词和时间段就行，如果需要限制微博类型或者地点就根据url的格式加上新的限制条件。
> 3. 您的意思是指查找具有某几个关键词的微博吗？可以考虑建个字典对url进行更新。数据库中可以添加相应的字段进行区分。
> 4. 您需要把这个问题再具体一点，我们也不太清楚您说的具体是哪个部分出现了这个错误，我们之前运行的时候是没有出现这个问题的。

**Comment by lovesnacks** [comment]
我把个人信息那部分注释去掉尝试了一下，在数据库中没有生成information这个collection，我会再尝试一下。

我对url加了限制条件region=custom:xx:xx没有用，是因为weibo.cn这个站点的搜索条件不包括地点吗？好像只有weibo.com才有高级搜索如地点的功能，我可以直接把全部的weibo.cn改成weibo.com吗？这两个的搜索条件是一样的吗，我不太懂。

我要查找的不是同时具有几个关键词，而是单个关键词分别查，比如对“高温”查一次，对“低温”查一次，但是它们的数据都是放在同一个sina数据库的同样的tweets里面，所以我想加一列字段区分每一条记录是由哪个keyword得到的，这个麻烦吗？我比较小白。。。不太懂是应该对数据库操作还是对代码操作呢？

list index out of range大概就是爬一会数据会出现一会这些图上的提示，不知道对爬虫结果有没有影响
![image](https://user-images.githubusercontent.com/41772072/57074413-6011d400-6d16-11e9-86d3-0886cef3d520.png)

**Comment by seaweiqing** [comment]
哦对，你需要对比着看一下.com和.cn的url格式，两者的高级搜索功能是不一样的，我记得其中有一个是不包含地区的，.com的网络结构更加复杂，所以我们当时就用的.cn的高级搜索。

你后面的报错可能是.cn不包含region造成的吧，具体的你要自己去看看出错的地方在哪里。

查找多个关键词的就是我之前说的，你可以建一个list，在构建url的时候从list里面逐个抽取元素加到url里面。

information我们之前收集过，确实是没有问题的，如果你之后尝试了还是没有这个部分的数据我们可以试着再跑一下看看代码有没有什么问题。

**Comment by lovesnacks** [comment]
好的！！！谢谢您！！
